apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: demo-graphql-config-files
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: demo-graphql
    app.kubernetes.io/version: 0.1.7
  name: demo-graphql-app-server
  namespace: staging-demo-graphql
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: demo-graphql-app-server-c8feae02
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app-server
        app.kubernetes.io/instance: staging
        app.kubernetes.io/name: demo-graphql
        app.kubernetes.io/version: 0.1.7
        cdk8s.io/metadata.addr: demo-graphql-app-server-c8feae02
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - node
            - /app/applications/demo-graphql/dist/app-server.js
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config.json
          image: ghcr.io/mxvincent/demo-graphql:0.1.7
          imagePullPolicy: Always
          name: app-server
          ports:
            - containerPort: 4000
              name: http
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/config.json
              name: secret-demo-graphql-config-files
              subPath: config.json
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secret-demo-graphql-config-files
          secret:
            secretName: demo-graphql-config-files
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: demo-graphql
    app.kubernetes.io/version: 0.1.7
  name: demo-graphql-app-server
  namespace: staging-demo-graphql
spec:
  externalIPs: []
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    cdk8s.io/metadata.addr: demo-graphql-app-server-c8feae02
  type: ClusterIP
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: demo-graphql
    app.kubernetes.io/version: 0.1.7
  name: demo-graphql-config-files-secrets
  namespace: staging-demo-graphql
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:staging-demo-graphql
        metadataPolicy: None
        property: POSTGRES_DATABASE
        version: latest
      secretKey: STAGING_DEMO_GRAPHQL_POSTGRES_DATABASE
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:staging-demo-graphql
        metadataPolicy: None
        property: POSTGRES_USERNAME
        version: latest
      secretKey: STAGING_DEMO_GRAPHQL_POSTGRES_USERNAME
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:staging-demo-graphql
        metadataPolicy: None
        property: POSTGRES_PASSWORD
        version: latest
      secretKey: STAGING_DEMO_GRAPHQL_POSTGRES_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway
  target:
    creationPolicy: Owner
    name: demo-graphql-config-files
    template:
      data:
        config.json: '{"logLevel":"info","database":{"type":"postgres","host":"postgres-15-postgresql.postgres-15.svc.cluster.local","port":5432,"database":"STAGING_DEMO_GRAPHQL_POSTGRES_DATABASE | toString","username":"STAGING_DEMO_GRAPHQL_POSTGRES_USERNAME | toString","password":"STAGING_DEMO_GRAPHQL_POSTGRES_PASSWORD | toString"}}'
      engineVersion: "2"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme
    ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: staging
    app.kubernetes.io/name: demo-graphql
    app.kubernetes.io/version: 0.1.7
  name: demo-graphql-app-server
  namespace: staging-demo-graphql
spec:
  rules:
    - host: staging.demo-graphql.row.ovh
      http:
        paths:
          - backend:
              service:
                name: demo-graphql-app-server
                port:
                  number: 4000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - staging.demo-graphql.row.ovh
      secretName: demo-graphql-app-server-cert
