apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: experience-b-config
  labels:
    app.kubernetes.io/component: app-server
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: experience-b
    app.kubernetes.io/version: 0.0.1
  name: experience-b-app-server
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: development-experience-b-app-server-deployment-c8c56c24
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app-server
        app.kubernetes.io/instance: development
        app.kubernetes.io/name: experience-b
        app.kubernetes.io/version: 0.0.1
        cdk8s.io/metadata.addr: development-experience-b-app-server-deployment-c8c56c24
      name: experience-b-app-server
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - /nodejs/bin/node
            - /app/dist/app-server.js
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config/config.json
          image: ghcr.io/mxvincent/experience-b:0.0.1
          imagePullPolicy: Always
          name: app-server
          ports:
            - containerPort: 4000
              name: http
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/config/config.json
              name: config
              subPath: config.json
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            secretName: experience-b-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: experience-b
    app.kubernetes.io/version: 0.0.1
  name: experience-b-app-server
spec:
  externalIPs: []
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    cdk8s.io/metadata.addr: development-experience-b-app-server-deployment-c8c56c24
  type: ClusterIP
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: experience-b
    app.kubernetes.io/version: 0.0.1
  name: experience-b-config
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:development-experience-b
        metadataPolicy: None
        property: POSTGRES_HOST
        version: latest
      secretKey: DEVELOPMENT_EXPERIENCE_B_POSTGRES_HOST
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:development-experience-b
        metadataPolicy: None
        property: POSTGRES_PORT
        version: latest
      secretKey: DEVELOPMENT_EXPERIENCE_B_POSTGRES_PORT
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:development-experience-b
        metadataPolicy: None
        property: POSTGRES_DATABASE
        version: latest
      secretKey: DEVELOPMENT_EXPERIENCE_B_POSTGRES_DATABASE
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:development-experience-b
        metadataPolicy: None
        property: POSTGRES_USERNAME
        version: latest
      secretKey: DEVELOPMENT_EXPERIENCE_B_POSTGRES_USERNAME
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: name:development-experience-b
        metadataPolicy: None
        property: POSTGRES_PASSWORD
        version: latest
      secretKey: DEVELOPMENT_EXPERIENCE_B_POSTGRES_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway
  target:
    creationPolicy: Owner
    name: experience-b-config
    template:
      data:
        config.json: '{"server":{"host":"0.0.0.0","keepAliveTimeoutInMilliseconds":61000},"app":{"logLevel":"info","timeZone":"UTC"},"database":{"type":"postgres","host":"{{ .DEVELOPMENT_EXPERIENCE_B_POSTGRES_HOST | toString }}","port":"{{ .DEVELOPMENT_EXPERIENCE_B_POSTGRES_PORT | toString }}","database":"{{ .DEVELOPMENT_EXPERIENCE_B_POSTGRES_DATABASE | toString }}","username":"{{ .DEVELOPMENT_EXPERIENCE_B_POSTGRES_USERNAME | toString }}","password":"{{ .DEVELOPMENT_EXPERIENCE_B_POSTGRES_PASSWORD | toString }}"}}'
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/instance: development
          app.kubernetes.io/name: experience-b
          app.kubernetes.io/version: 0.0.1
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: Replace=true
    secret.reloader.stakater.com/reload: experience-b-config
  labels:
    app.kubernetes.io/component: debug
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: experience-b
    app.kubernetes.io/version: 0.0.1
  name: experience-b-debug
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: debug
        app.kubernetes.io/instance: development
        app.kubernetes.io/name: experience-b
        app.kubernetes.io/version: 0.0.1
        cdk8s.io/metadata.addr: development-experience-b-debug-c8053197
      name: experience-b-debug
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - /nodejs/bin/node
            - /app/dist/sandbox.js
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config/config.json
          image: ghcr.io/mxvincent/experience-b:0.0.1
          imagePullPolicy: Always
          name: debug
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/config/config.json
              name: config
              subPath: config.json
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            secretName: experience-b-config
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: Replace=true
    secret.reloader.stakater.com/reload: experience-b-config
  labels:
    app.kubernetes.io/component: sync-database-schema
    app.kubernetes.io/instance: development
    app.kubernetes.io/name: experience-b
    app.kubernetes.io/version: 0.0.1
  name: experience-b-sync-database-schema
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sync-database-schema
        app.kubernetes.io/instance: development
        app.kubernetes.io/name: experience-b
        app.kubernetes.io/version: 0.0.1
        cdk8s.io/metadata.addr: development-experience-b-sync-database-schema-c847e61a
      name: experience-b-sync-database-schema
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - /nodejs/bin/node
            - /app/dist/database/commands/migrate.js
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config/config.json
          image: ghcr.io/mxvincent/experience-b:0.0.1
          imagePullPolicy: Always
          name: sync-database-schema
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/config/config.json
              name: config
              subPath: config.json
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            secretName: experience-b-config
